__title__ = "trino-dask"
__description__ = "dask integration for trino"
__url__ = "https://github.com/posulliv/dask-trino"
__version__ = "0.1.0"
__author__ = "Padraig O'Sullivan"
__author_email__ = "padraig.osullivan@starburstdata.com"
